### ISSUE TITLE
Will there be a mac version/port

### ISSUE THREAD

**Issue by JosephIsATalonMain** [kuroni/bongocat-osu#90] opened 2020-10-20 20:24 UTC
Hey I am wondering if there will be a mac port of this plugin. 

I have found this plugin however, it appears to me that its only a keyboard and it's hard for me to install.
[](https://github.com/111116/mac-typing-bongo-cat)

**Comment by kuroni** [comment] 2020-10-26 20:49
Closed because duplicate of #89.

Personally I don't know how to use MacOS, or have any previous experience with it, so it's best if someone knows how to port it :(

I believe you can build this from scratch just like Linux, but I need someone using Mac to test this out.

**Closed by kuroni** 2020-10-26 20:49 UTC
