### ISSUE TITLE
Right hand not changing

### ISSUE THREAD

**Issue by NyannRR** [kuroni/bongocat-osu#79] opened 2020-09-13 04:05 UTC
I Tried changing all the hands in the textures, but nothing works, how could change the right hand to another image?

**Comment by mlucap** [comment] 2020-09-14 16:18
You need to give more information than that. What went wrong, what did you do etc. I was able to change the textures no problem. Make sure you reload the program after changing any textures.

**Comment by NyannRR** [comment] 2020-09-15 03:35
> You need to give more information than that. What went wrong, what did you do etc. I was able to change the textures no problem. Make sure you reload the program after changing any textures.

I Reloaded it, the problem is, i can change the left hand texture, but not the right one's texture, idk why since i tried changing all the hand textures in the textures folder.

**Comment by CSaratakij** [comment] 2020-09-15 04:15
Okay, your bongo cat is in the OSU! mode.
The paw that use to show how your mouse or pen tablet behave need to draw programmatically.

Right now, you can only change its paw color.

The way it draw right now use only the solid color.
That's why it won't change to the texture you want because those right paw texture will use only when in other mode such as Taiko, Mania, etc..

Because we can just swap a sprite texture in those particular mode and get away with that, thing is not that simple for the right paw in OSU! mode.

To make right paw with texture works, we need to change how we draw the right paw then wrap and bend our texture properly.
Kinda like the same thing that [Spine2D](http://esotericsoftware.com/) did.

PR welcome :D

**Comment by kuroni** [comment] 2020-09-28 02:10
Sorry trying to cleanup.

Duplicate of #27. I haven't found a way to add a picture to the right hand yet :(

**Closed by kuroni** 2020-09-28 02:10 UTC
