### ISSUE TITLE
Can't Change the right paw in Bongo Cat

### ISSUE THREAD

**Issue by Thusia0405** [kuroni/bongocat-osu#99] opened 2020-11-14 16:53 UTC
I'm trying to fully customize my bongo cat into another character, but i've issues changing the right paw, is there a solution to this problem?

**Comment by peeteer1245** [comment] 2020-11-28 02:03
Can you elaborate on your issue?

When you want to modify the images for non-custom modes you need to modify or replace the original files.
The important parts are that the name of the files need to be correct and that the resolution is the same.

If you want to change the image of the mouse for example, you can open the file `img/osu/mouse.png` in your favorite picture editor, make your changes and save. After that you reload bongocat (Ctrl + R) or open it again. Your changes should be visible.

**Comment by kuroni** [comment] 2020-12-25 22:38
Duplicate of #95 I believe.

**Closed by kuroni** 2020-12-25 22:38 UTC
