### ISSUE TITLE
can not change the size of the screen

### ISSUE THREAD

**Issue by picolojunior** [kuroni/bongocat-osu#47] opened 2020-06-03 07:27 UTC
"letterboxing": false,
        "width": 1920,
        "height": 1920,

No matter how many time i try modify in config.jason the screen window still same length did i do something wrong?

**Comment by kuroni** [comment] 2020-06-03 13:50
Those parameters are not for the bongocat's window size, it's the actual size of your monitor for bongocat to map the mouse input. Feel free to continue asking in this, although I will close this because this is not a bug.

**Closed by kuroni** 2020-06-03 13:50 UTC

**Comment by picolojunior** [comment] 2020-06-04 12:20
So we need to modify in the code only for the window size? Saw someone modify it and change to pengu name program something.
