### ISSUE TITLE
Can you add window top and size adjustment?

### ISSUE THREAD

**Issue by bubu-nono** [kuroni/bongocat-osu#76] opened 2020-09-04 09:28 UTC

**Comment by kuroni** [comment] 2020-09-14 19:22
I'm sorry I haven't been able to answer issues lately :(

I can try to do that but it's not in high priority. One thing you can do is to change the size of the overlay in OBS (or any streaming suite you're using).

**Comment by kuroni** [comment] 2020-09-28 02:12
Duplicate of #60

**Closed by kuroni** 2020-09-28 02:12 UTC
