### ISSUE TITLE
Moving paw 

### ISSUE THREAD

**Issue by Alex20cm** [kuroni/bongocat-osu#91] opened 2020-10-25 05:07 UTC
Hello do you reckon is it possible to change the mowing paw like a normal human hand? as i do see some streamers having like a cartoon character but the moving hand is changed isn't like this. thank you

**Comment by kuroni** [comment] 2020-10-26 20:47
It's a duplicate of #27 . Sadly I don't think I will implement this, because it is too much work and I am not motivated to do so :(

**Closed by kuroni** 2020-10-26 20:47 UTC
